const data = {
    products:[
        {
            name:'Nike slime shirt',
            category: 'shirts',
            image: '/images/p1.jpg',
            price:120,
            countInStock: 10,
            brand:'nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quatity product',
        },
        {
            name:'Adidas fit shirts shirt',
            category: 'shirts',
            image:'/images/p2.jpg',
            price:100,
            countInStock: 20,
            brand:'adidas',
            rating: 4.0,
            numReviews: 10,
            description: 'high quatity product',
        },    {
            name:'Lacoste free shirt',
            category: 'shirts',
            image:'/images/p3.jpg',
            price:220,
            countInStock: 0,
            brand:'lacoste',
            rating: 4.8,
            numReviews: 17,
            description: 'high quatity product',
        },    {
            name:'Nike slime pant',
            category: 'pant',
            image:'/images/p4.jpg',
            price:78,
            countInStock: 15,
            brand:'nike',
            rating: 4.5,
            numReviews: 14,
            description: 'high quatity product',
        },    {
            name:'puma slime pant',
            category: 'pant',
            image:'/images/p5.jpg',
            price:65,
            countInStock: 5,
            brand:'puma',
            rating: 4.5,
            numReviews: 10,
            description: 'high quatity product',
        },    {
            name:'adidas fit pant',
            category: 'pant',
            image:'/images/p6.jpg',
            price:139,
            countInStock: 12,
            brand:'adidas',
            rating: 4.5,
            numReviews: 15,
            description: 'high quatity product',
        },  {
            name:'cronic super electronic pack',
            category:'electronics',
            image:'image/p7.jpg',
            price:150000,
            countInStoack: 10,
            brand:'cronic',
            rating:4.5,
            numReview: 15,
            description: 'high quality product',
        }
    ],
}
export default data;
